# Generated by Django 4.2.4 on 2023-09-19 09:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import questionapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('file_type', models.SmallIntegerField(blank=True, null=True)),
                ('report_count', models.PositiveIntegerField(blank=True, null=True)),
                ('Upvote', models.PositiveIntegerField(blank=True, null=True)),
                ('downvote', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('answerby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.websiteuser')),
            ],
        ),
        migrations.CreateModel(
            name='Commentonanswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentanswerdetail', models.CharField(blank=True, max_length=1000, null=True)),
                ('Upvote', models.PositiveIntegerField(blank=True, null=True)),
                ('downvote', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('commentanswerwriter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.websiteuser')),
                ('useranswerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionapp.answerquestion')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(blank=True, max_length=1050, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('questionby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.websiteuser')),
            ],
        ),
        migrations.CreateModel(
            name='ReportOnAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintonanswer', models.CharField(blank=True, max_length=550, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.websiteuser')),
                ('reported_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionapp.answerquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyonCommentanswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replydetail', models.CharField(blank=True, max_length=1000, null=True)),
                ('Upvote', models.PositiveIntegerField(blank=True, null=True)),
                ('downvote', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Commentanswerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionapp.commentonanswer')),
                ('commentanswerreplyuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.websiteuser')),
                ('mainanswerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionapp.answerquestion')),
                ('subreplyofanswer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_replies', to='questionapp.replyoncommentanswer')),
            ],
        ),
        migrations.CreateModel(
            name='ImageonAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=questionapp.models.get_file_pathforquestion)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('useranswerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionapp.answerquestion')),
            ],
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='questionform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionapp.userquestion'),
        ),
    ]
